name: Run Python Script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install dependencies (if any)
      run: |
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Run Python file
      run: python file.py
